import type { CSSProperties } from "react";
import {
  Activity,
  AlertTriangle,
  Archive,
  ArrowLeft,
  ArrowRight,
  ArrowUpCircle,
  ArrowUp,
  Ban,
  Bookmark,
  BookmarkPlus,
  Bot,
  Box,
  Boxes,
  Braces,
  Building2,
  Calendar,
  CalendarX,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  Circle,
  CircleCheck,
  CircleDashed,
  CircleX,
  Clock,
  Cpu,
  CornerDownRight,
  Copy,
  CreditCard,
  Database,
  Download,
  File,
  FileArchive,
  FileCode,
  FileText,
  Filter,
  Flame,
  Github,
  GitBranch,
  GitCommit,
  Globe,
  Hash,
  Heart,
  History,
  Image,
  Laptop,
  Layers,
  Link2,
  Loader,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Megaphone,
  MessageSquare,
  Monitor,
  Moon,
  MoreHorizontal,
  Package,
  Package2,
  Palette,
  Paperclip,
  PanelLeftClose,
  PanelLeftOpen,
  PanelRight,
  Pencil,
  PenTool,
  Pin,
  Plus,
  PlugZap,
  Rocket,
  Sun,
  RotateCcw,
  Search,
  SearchX,
  Send,
  Settings,
  Shield,
  SquareStack,
  Star,
  Tag,
  Table2,
  Upload,
  UploadCloud,
  User,
  UserMinus,
  UserPlus,
  Users,
  X,
  Code,
  Eye,
  EyeOff,
  ExternalLink,
  FilePenLine,
  Folder,
  FolderOpen,
  FolderPlus,
  Info,
  Key,
  KeyRound,
  PackageOpen,
  RefreshCw,
  Reply,
  ShieldCheck,
  SmilePlus,
  Sparkles,
  SquarePen,
  Terminal,
  Trash2,
  Unlock,
  Zap,
  type LucideIcon,
} from "lucide-react";

/** Lucide line icons, looked up by the design's data-lucide names. 1.75 stroke. */
const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  "alert-triangle": AlertTriangle,
  archive: Archive,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  "arrow-up-circle": ArrowUpCircle,
  ban: Ban,
  bookmark: Bookmark,
  "bookmark-plus": BookmarkPlus,
  bot: Bot,
  box: Box,
  boxes: Boxes,
  braces: Braces,
  "building-2": Building2,
  calendar: Calendar,
  "calendar-x": CalendarX,
  check: Check,
  "check-circle-2": CheckCircle2,
  "circle-check": CircleCheck,
  "circle-x": CircleX,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "chevrons-up-down": ChevronsUpDown,
  circle: Circle,
  "circle-dashed": CircleDashed,
  clock: Clock,
  copy: Copy,
  "credit-card": CreditCard,
  database: Database,
  cpu: Cpu,
  "corner-down-right": CornerDownRight,
  download: Download,
  file: File,
  "file-archive": FileArchive,
  "file-code": FileCode,
  "file-text": FileText,
  filter: Filter,
  flame: Flame,
  "git-branch": GitBranch,
  "git-commit": GitCommit,
  github: Github,
  globe: Globe,
  hash: Hash,
  heart: Heart,
  history: History,
  image: Image,
  laptop: Laptop,
  layers: Layers,
  "link-2": Link2,
  loader: Loader,
  lock: Lock,
  "log-in": LogIn,
  "log-out": LogOut,
  mail: Mail,
  megaphone: Megaphone,
  "message-square": MessageSquare,
  monitor: Monitor,
  moon: Moon,
  "more-horizontal": MoreHorizontal,
  package: Package,
  "package-2": Package2,
  "package-open": PackageOpen,
  palette: Palette,
  paperclip: Paperclip,
  "panel-left-close": PanelLeftClose,
  "panel-left-open": PanelLeftOpen,
  "panel-right": PanelRight,
  pencil: Pencil,
  "pen-tool": PenTool,
  pin: Pin,
  plus: Plus,
  "plug-zap": PlugZap,
  rocket: Rocket,
  sun: Sun,
  "rotate-ccw": RotateCcw,
  search: Search,
  "search-x": SearchX,
  send: Send,
  settings: Settings,
  shield: Shield,
  "square-stack": SquareStack,
  star: Star,
  tag: Tag,
  table: Table2,
  "trash-2": Trash2,
  upload: Upload,
  "upload-cloud": UploadCloud,
  user: User,
  "user-minus": UserMinus,
  "user-plus": UserPlus,
  users: Users,
  x: X,
  code: Code,
  eye: Eye,
  "eye-off": EyeOff,
  "external-link": ExternalLink,
  "file-pen-line": FilePenLine,
  folder: Folder,
  "folder-open": FolderOpen,
  "folder-plus": FolderPlus,
  info: Info,
  key: Key,
  "key-round": KeyRound,
  "refresh-cw": RefreshCw,
  reply: Reply,
  "shield-check": ShieldCheck,
  "smile-plus": SmilePlus,
  sparkles: Sparkles,
  "square-pen": SquarePen,
  terminal: Terminal,
  unlock: Unlock,
  zap: Zap,
};

export function Icon({
  name,
  size = 16,
  className,
  style,
}: {
  name: string;
  size?: number;
  className?: string;
  style?: CSSProperties;
}) {
  const Cmp = ICONS[name] ?? Package;
  return <Cmp size={size} strokeWidth={1.75} className={className} style={style} aria-hidden="true" />;
}
