-- Hosted Companions are retired. Never erase the inventory of live external resources.
-- Stop the previous runtime and permanently delete its Companions through the previous release
-- before deploying this migration. Skill data and queued object cleanup remain untouched.
LOCK TABLE public.companions, public.companion_images, public.companion_runtime_duplicate_cleanups,
  public.companion_runtime_instances, public.companion_v3_instances, public.companion_triggers,
  public.companion_legacy_purge_targets, public.companion_v2_purge_targets IN ACCESS EXCLUSIVE MODE;
--> statement-breakpoint

DO $retire_guard$
BEGIN
  IF EXISTS (SELECT 1 FROM public.companions)
    OR EXISTS (SELECT 1 FROM public.companion_images)
    OR EXISTS (SELECT 1 FROM public.companion_runtime_duplicate_cleanups)
    OR EXISTS (SELECT 1 FROM public.companion_runtime_instances WHERE box_id IS NOT NULL)
    OR EXISTS (SELECT 1 FROM public.companion_v3_instances WHERE box_id IS NOT NULL)
    OR EXISTS (SELECT 1 FROM public.companion_triggers)
    OR EXISTS (SELECT 1 FROM public.companion_legacy_purge_targets WHERE state NOT IN ('completed', 'absent'))
    OR EXISTS (SELECT 1 FROM public.companion_v2_purge_targets WHERE state NOT IN ('completed', 'absent'))
  THEN
    RAISE EXCEPTION 'Hosted Companion retirement requires external resource cleanup with the previous release first';
  END IF;
END
$retire_guard$;
--> statement-breakpoint

-- A runtime-minted credential must never turn into an ordinary member PAT after retirement.
DELETE FROM public.api_tokens WHERE source_type = 'companion';
--> statement-breakpoint

CREATE OR REPLACE FUNCTION companion_complete_skill_database_object_deletion(p_storage_key text, p_claim_token uuid)
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  WITH deleted AS (
    DELETE FROM public.skill_database_object_deletions
    WHERE storage_key = p_storage_key
      AND claim_token = p_claim_token
    RETURNING 1
  )
  SELECT EXISTS (SELECT 1 FROM deleted);
$$;

--> statement-breakpoint
ALTER TABLE public.skill_database_object_deletions DROP COLUMN companion_attachment_id;
--> statement-breakpoint

-- Explicit function inventory from the final hosted release; Skills Hub functions are retained.
DO $retire_functions$
DECLARE target record;
BEGIN
  FOR target IN
    SELECT p.oid::regprocedure AS signature
    FROM pg_catalog.pg_proc p
    JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public' AND p.proname = ANY (ARRAY[
      'companion_api_actor',
      'companion_api_answer_config_decision',
      'companion_api_answer_decision',
      'companion_api_answer_routine_decision',
      'companion_api_answer_trigger_decision',
      'companion_api_assert_message_attachments',
      'companion_api_assign_attempt_retry_id',
      'companion_api_assign_section',
      'companion_api_bump_skill_revision',
      'companion_api_cancel_turn',
      'companion_api_config_merge_ids',
      'companion_api_create_companion',
      'companion_api_create_control_request',
      'companion_api_create_routine',
      'companion_api_create_section',
      'companion_api_create_trigger',
      'companion_api_decide_control_request',
      'companion_api_delete_routine',
      'companion_api_delete_section',
      'companion_api_delete_trigger',
      'companion_api_enqueue_control_continuation',
      'companion_api_enqueue_delegation',
      'companion_api_enqueue_operation',
      'companion_api_enqueue_turn',
      'companion_api_fail_trigger_fire',
      'companion_api_finish_control_invocation',
      'companion_api_finish_control_request',
      'companion_api_fire_trigger',
      'companion_api_get_control_request',
      'companion_api_get_decision',
      'companion_api_get_delegation',
      'companion_api_get_plugin_trigger_key',
      'companion_api_get_routine_run',
      'companion_api_get_routine_run_v2',
      'companion_api_get_trigger_for_registration',
      'companion_api_get_trigger_run',
      'companion_api_get_trigger_run_v2',
      'companion_api_grant_peer_access',
      'companion_api_list_delegations',
      'companion_api_list_peers',
      'companion_api_list_routine_runs',
      'companion_api_list_routine_runs_v2',
      'companion_api_list_routines',
      'companion_api_list_runtime',
      'companion_api_list_sections',
      'companion_api_list_skill_sync',
      'companion_api_list_trigger_provider_accounts',
      'companion_api_list_trigger_runs',
      'companion_api_list_trigger_runs_v2',
      'companion_api_list_triggers',
      'companion_api_lock_selected_mcp_account',
      'companion_api_mark_thread_read',
      'companion_api_message_attachment_intent',
      'companion_api_operation_json',
      'companion_api_read_attachment',
      'companion_api_read_runtime',
      'companion_api_read_skill_sync',
      'companion_api_read_thread',
      'companion_api_read_thread_changes',
      'companion_api_read_thread_projection_sequence',
      'companion_api_read_thread_window',
      'companion_api_record_delegation',
      'companion_api_register_control_invocation',
      'companion_api_register_notification_device',
      'companion_api_reorder_sections',
      'companion_api_require_access',
      'companion_api_require_skill_revision',
      'companion_api_retry_operation_handoff',
      'companion_api_retry_turn',
      'companion_api_revoke_peer_access',
      'companion_api_rotate_trigger_secret',
      'companion_api_routine_hidden_relay_turns',
      'companion_api_routine_json',
      'companion_api_routine_notify_returns',
      'companion_api_routine_notify_returns_window',
      'companion_api_routine_run_json',
      'companion_api_routine_run_json_v2',
      'companion_api_routine_run_summary_json',
      'companion_api_safe_error',
      'companion_api_schedule_pi_restart',
      'companion_api_set_initial_provider',
      'companion_api_set_plugin_trigger_key',
      'companion_api_set_trigger_registration',
      'companion_api_set_workspace_access',
      'companion_api_stored_attachment_intent',
      'companion_api_sync_thread',
      'companion_api_thread_entry_json',
      'companion_api_thread_entry_visible',
      'companion_api_thread_metadata',
      'companion_api_trigger_json',
      'companion_api_trigger_run_json',
      'companion_api_trigger_run_json_v2',
      'companion_api_trigger_run_summary_json',
      'companion_api_turn_json',
      'companion_api_turn_recovery_status',
      'companion_api_unregister_notification_device',
      'companion_api_update_companion',
      'companion_api_update_member_state',
      'companion_api_update_member_state_v2',
      'companion_api_update_routine',
      'companion_api_update_section',
      'companion_api_update_trigger',
      'companion_api_v3_routine_run_json',
      'companion_api_v3_trigger_run_json',
      'companion_api_validate_resource_selection',
      'companion_assign_transcript_turn',
      'companion_associate_turn_transcript',
      'companion_cancel_queued_routine_on_change',
      'companion_cancel_queued_routine_turns',
      'companion_capture_routine_snapshot',
      'companion_claim_due_routines',
      'companion_claim_notification_deliveries',
      'companion_claim_notification_deliveries_v2',
      'companion_complete_notification_delivery',
      'companion_control_normalize_native_settings_material',
      'companion_defer_notification_delivery',
      'companion_degrade_trigger_provider_account',
      'companion_disconnect_trigger_provider_for_mcp',
      'companion_enqueue_attachment_object_deletion',
      'companion_enqueue_deferred_pi_restart',
      'companion_fail_routine_fire',
      'companion_finalize_v2_purge',
      'companion_fire_routine',
      'companion_invalidate_notification_device',
      'companion_notification_enqueue',
      'companion_notification_pending_decision',
      'companion_notification_terminal_turn',
      'companion_preserve_tool_run_identity',
      'companion_record_routine_run_outcome',
      'companion_record_trigger_run_outcome',
      'companion_resolve_control_token',
      'companion_resolve_mcp_broker_token',
      'companion_revoke_inactive_control_token',
      'companion_revoke_inactive_mcp_broker_token',
      'companion_runtime_assign_attempt_lane',
      'companion_runtime_assign_attempt_snapshot',
      'companion_runtime_assign_operation_intent',
      'companion_runtime_assign_turn_sequence',
      'companion_runtime_authorize_desktop',
      'companion_runtime_cas_mcp_oauth',
      'companion_runtime_checkpoint',
      'companion_runtime_checkpoint_duplicate_cleanup',
      'companion_runtime_claim_work',
      'companion_runtime_claim_work_material_v1',
      'companion_runtime_claim_work_without_delete_resume_guard',
      'companion_runtime_claim_work_without_material_guard',
      'companion_runtime_close_attempt_decisions',
      'companion_runtime_commit_skill_update',
      'companion_runtime_consume_desktop_request',
      'companion_runtime_create_lease_row',
      'companion_runtime_defer_busy_turn_start',
      'companion_runtime_defer_delete',
      'companion_runtime_disable',
      'companion_runtime_enable',
      'companion_runtime_enqueue_interrupted_recovery',
      'companion_runtime_ensure_turn_recovery',
      'companion_runtime_expire_queued_routine_turns',
      'companion_runtime_gate_status',
      'companion_runtime_get_attempt_terminal_projection',
      'companion_runtime_get_config_catalog',
      'companion_runtime_get_material',
      'companion_runtime_get_material_before_attachment_retention',
      'companion_runtime_get_routine_material',
      'companion_runtime_get_skill_update_material',
      'companion_runtime_get_trigger_material',
      'companion_runtime_get_turn_context',
      'companion_runtime_guard_duplicate_cleanup',
      'companion_runtime_image_authorize_publish',
      'companion_runtime_image_claim',
      'companion_runtime_image_clear_building_box',
      'companion_runtime_image_get',
      'companion_runtime_image_mark_building_box',
      'companion_runtime_image_mark_delete_intent',
      'companion_runtime_image_mark_delete_operation',
      'companion_runtime_image_record_failure',
      'companion_runtime_image_record_ready',
      'companion_runtime_image_request',
      'companion_runtime_keep_available_skill_revision',
      'companion_runtime_main_turn_material_ready',
      'companion_runtime_mint_control_token',
      'companion_runtime_mint_hub_token',
      'companion_runtime_mint_mcp_broker_token',
      'companion_runtime_normalize_legacy_recovery_snapshot',
      'companion_runtime_normalize_terminal_interruption',
      'companion_runtime_observe_instance',
      'companion_runtime_operation_lane',
      'companion_runtime_pause_needs_input_inactivity',
      'companion_runtime_prepare_isolated_run_internal',
      'companion_runtime_prepare_queued_turn_material',
      'companion_runtime_prepare_routine_run',
      'companion_runtime_project_automatic_decision_close',
      'companion_runtime_project_event_batch',
      'companion_runtime_project_event_batch_v2',
      'companion_runtime_publish_material_snapshot',
      'companion_runtime_reconcile_projected_decision_with_member_turn',
      'companion_runtime_reconcile_settled_turn_starts',
      'companion_runtime_record_attempt_outputs',
      'companion_runtime_record_material_snapshot',
      'companion_runtime_record_skill_update_error',
      'companion_runtime_recovery_metrics',
      'companion_runtime_register_duplicate_cleanups',
      'companion_runtime_reject_actor_change',
      'companion_runtime_reject_attempt_snapshot_change',
      'companion_runtime_reject_operation_snapshot_change',
      'companion_runtime_reject_responder_change',
      'companion_runtime_reject_turn_surface_change',
      'companion_runtime_release_lease',
      'companion_runtime_renew_and_authorize',
      'companion_runtime_renew_and_authorize_v2',
      'companion_runtime_renew_and_authorize_v3',
      'companion_runtime_repair_legacy_material_work',
      'companion_runtime_reset_material_on_pi_change',
      'companion_runtime_reset_settings_material_snapshot',
      'companion_runtime_resume_after_decision_delivery',
      'companion_runtime_routine_lane_quiescent',
      'companion_runtime_settle',
      'companion_runtime_settle_recovery_operation',
      'companion_runtime_supersede_decision_on_member_turn',
      'companion_runtime_surface_isolated_return_internal',
      'companion_runtime_surface_routine_return',
      'companion_runtime_turn_lane',
      'companion_schedule_attachment_expiry',
      'companion_set_attachment_expiry',
      'companion_surface_delegation_result',
      'companion_thread_allocate_projection_sequence',
      'companion_thread_sequence_entry',
      'companion_thread_touch_attachment_entry',
      'companion_thread_touch_recovery_operation',
      'companion_thread_touch_routine_return',
      'companion_thread_touch_turn_entry',
      'companion_v2_purge_ledger_immutable',
      'companion_v2_purge_preservation_fingerprint',
      'companion_v3_admit_turn',
      'companion_v3_api_admit_turn',
      'companion_v3_api_answer_decision',
      'companion_v3_api_bump_skill_revision',
      'companion_v3_api_cancel_delegation_turn',
      'companion_v3_api_cancel_turn',
      'companion_v3_api_create_companion',
      'companion_v3_api_desire_lifecycle',
      'companion_v3_api_enqueue_turn',
      'companion_v3_api_enqueue_warm_turn',
      'companion_v3_api_enqueue_warm_turn_v5',
      'companion_v3_api_get_decision',
      'companion_v3_api_list_runtime',
      'companion_v3_api_list_skill_sync',
      'companion_v3_api_read_projection',
      'companion_v3_api_read_runtime',
      'companion_v3_api_read_skill_sync',
      'companion_v3_api_request_pi_recycle',
      'companion_v3_api_require_skill_revision',
      'companion_v3_api_set_initial_provider',
      'companion_v3_api_update_companion',
      'companion_v3_api_update_member_state',
      'companion_v3_bound_preparation_clock',
      'companion_v3_bound_turn_clocks',
      'companion_v3_build_recovery_context',
      'companion_v3_cancel_queued_routine_turns',
      'companion_v3_expire_preparation',
      'companion_v3_fence_runtime_gate',
      'companion_v3_invalidate_from_companion',
      'companion_v3_invalidate_from_resource',
      'companion_v3_invalidate_from_turn',
      'companion_v3_invalidate_preparation',
      'companion_v3_mark_delegation_delivery_failed',
      'companion_v3_measure_acceptance',
      'companion_v3_measure_claim',
      'companion_v3_measure_progress',
      'companion_v3_note_admitted_work',
      'companion_v3_preempt_routine_for_delete',
      'companion_v3_public_turn',
      'companion_v3_release_recovery_reservation',
      'companion_v3_restage_consumed_preparation',
      'companion_v3_routine_preparation_matches',
      'companion_v3_runtime_ack_external_incident_signal_v9',
      'companion_v3_runtime_authorize_background_v8',
      'companion_v3_runtime_authorize_background_v9',
      'companion_v3_runtime_authorize_routine',
      'companion_v3_runtime_authorize_routine_internal_v7',
      'companion_v3_runtime_authorize_warm_turn',
      'companion_v3_runtime_authorize_warm_turn_v5',
      'companion_v3_runtime_authorize_warm_turn_v7',
      'companion_v3_runtime_authorize_warm_turn_v8',
      'companion_v3_runtime_authorize_warm_unchecked',
      'companion_v3_runtime_begin_admission',
      'companion_v3_runtime_begin_admission_v5',
      'companion_v3_runtime_begin_background_admission_v9',
      'companion_v3_runtime_begin_decision_action',
      'companion_v3_runtime_begin_routine_admission',
      'companion_v3_runtime_checkpoint_lifecycle',
      'companion_v3_runtime_checkpoint_pi_recycle',
      'companion_v3_runtime_checkpoint_preparation',
      'companion_v3_runtime_checkpoint_preparation_v6',
      'companion_v3_runtime_claim',
      'companion_v3_runtime_claim_background_internal_v7',
      'companion_v3_runtime_claim_background_v8',
      'companion_v3_runtime_claim_background_v9',
      'companion_v3_runtime_claim_external_incident_signal_v9',
      'companion_v3_runtime_claim_lifecycle',
      'companion_v3_runtime_claim_preparation',
      'companion_v3_runtime_claim_preparation_v5',
      'companion_v3_runtime_claim_preparation_v6',
      'companion_v3_runtime_claim_routine_v7',
      'companion_v3_runtime_claim_v4',
      'companion_v3_runtime_claim_warm',
      'companion_v3_runtime_claim_warm_unchecked',
      'companion_v3_runtime_claim_warm_v4',
      'companion_v3_runtime_claim_warm_v5',
      'companion_v3_runtime_claim_warm_v6',
      'companion_v3_runtime_claim_warm_v7',
      'companion_v3_runtime_claim_warm_v8',
      'companion_v3_runtime_claim_warm_v9',
      'companion_v3_runtime_complete',
      'companion_v3_runtime_complete_v4',
      'companion_v3_runtime_complete_v5',
      'companion_v3_runtime_complete_v6',
      'companion_v3_runtime_complete_v7',
      'companion_v3_runtime_complete_v8',
      'companion_v3_runtime_defer_external_v9',
      'companion_v3_runtime_defer_lifecycle',
      'companion_v3_runtime_defer_preparation',
      'companion_v3_runtime_defer_preparation_external_v9',
      'companion_v3_runtime_external_incident_facts_v9',
      'companion_v3_runtime_fail_preparation_v9',
      'companion_v3_runtime_finalize_delete',
      'companion_v3_runtime_finish_decision_action',
      'companion_v3_runtime_finish_delegation_cancel',
      'companion_v3_runtime_measurement_facts',
      'companion_v3_runtime_mint_preparation_credentials',
      'companion_v3_runtime_pending_delegation_cancel',
      'companion_v3_runtime_project_background_page_v10',
      'companion_v3_runtime_project_background_page_v7',
      'companion_v3_runtime_project_background_page_v8',
      'companion_v3_runtime_project_background_page_v9',
      'companion_v3_runtime_project_native_page',
      'companion_v3_runtime_project_native_page_v4',
      'companion_v3_runtime_project_native_page_v5',
      'companion_v3_runtime_project_native_page_v6',
      'companion_v3_runtime_project_native_page_v7',
      'companion_v3_runtime_project_native_page_v8',
      'companion_v3_runtime_project_page',
      'companion_v3_runtime_project_routine_page',
      'companion_v3_runtime_read_native_fallback_v8',
      'companion_v3_runtime_reauthorize_preparation',
      'companion_v3_runtime_reconcile_pi_recycle_invocation',
      'companion_v3_runtime_record_admission',
      'companion_v3_runtime_record_native_admission',
      'companion_v3_runtime_record_native_admission_v5',
      'companion_v3_runtime_record_native_fallback_v8',
      'companion_v3_runtime_record_terminal_model_error_v9',
      'companion_v3_runtime_record_turn_outputs',
      'companion_v3_runtime_recover_external_turn_v9',
      'companion_v3_runtime_recover_external_v9',
      'companion_v3_runtime_sweep_background_deadlines_v8',
      'companion_v3_runtime_sweep_deadlines',
      'companion_v3_runtime_sweep_decisions',
      'companion_v3_runtime_sweep_preparation_deadlines',
      'companion_v3_runtime_sweep_routine_deadlines_v7',
      'companion_v3_surface_delegation_result',
      'companion_v3_worker_admit_turn',
      'companion_validate_notification_delivery',
      'companion_webhook_get_trigger'
    ])
  LOOP
    EXECUTE format('DROP FUNCTION IF EXISTS %s CASCADE', target.signature);
  END LOOP;
END
$retire_functions$;
--> statement-breakpoint

DO $retire_tables$
DECLARE target record;
BEGIN
  FOR target IN SELECT tablename FROM pg_catalog.pg_tables
    WHERE schemaname = 'public' AND (tablename = 'companions' OR left(tablename, 10) = 'companion_')
  LOOP
    EXECUTE format('DROP TABLE IF EXISTS public.%I CASCADE', target.tablename);
  END LOOP;
  FOR target IN SELECT typname FROM pg_catalog.pg_type t
    JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace
    WHERE n.nspname = 'public' AND t.typtype = 'e' AND left(t.typname, 10) = 'companion_'
  LOOP
    EXECUTE format('DROP TYPE IF EXISTS public.%I CASCADE', target.typname);
  END LOOP;
END
$retire_tables$;

--> statement-breakpoint
ALTER TABLE public.organizations DROP COLUMN default_companion_provider_id;
