import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { skillpackSkillDir } from "@skillpack/skillpack-skill";
import { reportLocalSkillInstallInputSchema } from "@skillpack/contracts";
import { computeLocalSkillStatus } from "@skillpack/core/services";
import {
  buildSkillpackSkillPrompts,
  buildSkillpackSkillRow,
  getSkillpackSkillPackage,
} from "@skillpack/skillpack-skill/package";

const workspaceId = "org-1";

describe("computeLocalSkillStatus", () => {
  it("returns none when the member has never reported an install", () => {
    expect(computeLocalSkillStatus(null, "1.2.0")).toBe("none");
  });

  it("returns update when the installed version is behind the available version", () => {
    expect(computeLocalSkillStatus("1.1.0", "1.2.0")).toBe("update");
    expect(computeLocalSkillStatus("0.9.0", "1.0.0")).toBe("update");
  });

  it("returns installed when the installed version is current or ahead", () => {
    expect(computeLocalSkillStatus("1.2.0", "1.2.0")).toBe("installed");
    expect(computeLocalSkillStatus("1.3.0", "1.2.0")).toBe("installed");
  });
});

describe("reportLocalSkillInstallInputSchema", () => {
  it("accepts a valid semver with an optional agent label", () => {
    expect(reportLocalSkillInstallInputSchema.parse({ version: "1.0.0", agent: "Claude Code" })).toEqual({
      version: "1.0.0",
      agent: "Claude Code",
    });
    expect(reportLocalSkillInstallInputSchema.parse({ version: "2.3.4" })).toEqual({ version: "2.3.4" });
  });

  it("rejects a non-semver version", () => {
    expect(() => reportLocalSkillInstallInputSchema.parse({ version: "latest" })).toThrow();
  });
});

describe("companion skill package + row", () => {
  it("packs the bundled skill deterministically and reads its version", async () => {
    const pkg = await getSkillpackSkillPackage();
    expect(pkg.key).toBe("skillpack");
    expect(pkg.checksum).toMatch(/^sha256:[0-9a-f]{64}$/);
    expect(pkg.version).toBe("1.120.0");
    expect(pkg.sizeBytes).toBeGreaterThan(0);
    expect(pkg.integrity.packageChecksum).toBe(pkg.checksum);
    expect(pkg.integrity.files["SKILL.md"]).toMatch(/^sha256:[0-9a-f]{64}$/);
    expect(pkg.integrity.files["companion.json"]).toMatch(/^sha256:[0-9a-f]{64}$/);
    expect(pkg.integrity.files["companion.integrity.json"]).toMatch(/^sha256:[0-9a-f]{64}$/);
    expect(pkg.integrity.files["scripts/bootstrap.py"]).toMatch(/^sha256:[0-9a-f]{64}$/);
    expect(pkg.integrity.files["scripts/companion_lib.py"]).toMatch(/^sha256:[0-9a-f]{64}$/);

    // SAFETY: the committed integrity baseline is generated by update-integrity.mjs with exactly this shape.
    const baseline = JSON.parse(await readFile(join(skillpackSkillDir(), "companion.integrity.json"), "utf8")) as {
      schemaVersion?: unknown;
      version?: unknown;
      files?: Record<string, string>;
    };
    expect(baseline.schemaVersion).toBe(1);
    expect(baseline.version).toBe(pkg.version);
    expect(Object.keys(baseline.files ?? {}).sort()).toEqual([
      "SKILL.md",
      "companion.json",
      "evals/evals.json",
      "runtime-release.json",
      "scripts/bootstrap.py",
      "scripts/bootstrap_integrity.py",
      "scripts/bootstrap_update.py",
      "scripts/check_updates.py",
      "scripts/companion-agent-client.mjs",
      "scripts/companion_lib.py",
      "scripts/create_secret.py",
      "scripts/install_skill.py",
      "scripts/onboarding_scan.py",
      "scripts/opencode-runtime.mjs",
      "scripts/package-checksum.mjs",
      "scripts/runtime_command.py",
      "scripts/runtime_lock.py",
      "scripts/runtime_setup.py",
      "scripts/runtime_skill_sync.py",
      "scripts/secrets_runtime.py",
      "scripts/skill_guard.py",
      "scripts/skillpack-agent-client.mjs",
      "scripts/skillpack-runtime-launch.py",
      "scripts/sync_companion.py",
      "scripts/sync_secrets.py",
      "scripts/sync_skillpack.py",
      "scripts/tools.json",
      "scripts/verify-runtime-release.mjs",
    ]);
    for (const [relPath, digest] of Object.entries(baseline.files ?? {})) {
      const bytes = await readFile(join(skillpackSkillDir(), relPath));
      expect(digest).toBe(`sha256:${createHash("sha256").update(bytes).digest("hex")}`);
      expect(pkg.integrity.files[relPath]).toBe(digest);
    }
  });

  it("builds a 'none' row with an actionable install prompt for a fresh caller", async () => {
    const pkg = await getSkillpackSkillPackage();
    const row = await buildSkillpackSkillRow(null, workspaceId);
    expect(row.status).toBe("none");
    expect(row.workspaceId).toBe(workspaceId);
    expect(row.description).toContain("native CLI");
    expect(row.description).toContain("API key");
    expect(row.notes).toContain("companion.json");
    expect(row.notes).toContain("skills.lock.json");
    expect(row.installedVersion).toBeNull();
    expect(row.lastReportedAt).toBeNull();
    expect(row.availableVersion).toBe(pkg.version);
    expect(row.integrity.packageChecksum).toBe(pkg.checksum);
    expect(row.integrity.files["scripts/bootstrap.py"]).toMatch(/^sha256:[0-9a-f]{64}$/);
    expect(row.commands.length).toBeGreaterThan(0);
    expect(row.commands).toContainEqual({
      name: "Connect an agent",
      desc: "Connect the native CLI through browser approval or an API key and verify the selected workspace.",
    });
    expect(row.commands).toContainEqual({
      name: "Check CLI health",
      desc: "Inspect credentials, package integrity, hook setup and observed usage with skillpack doctor.",
    });
    expect(row.commands).toContainEqual({
      name: "Publish a skill",
      desc: "Validate a skill, ask Personal vs Org and folder placement, then publish it safely.",
    });
    expect(row.commands).toContainEqual({
      name: "Manage skill API calls",
      desc: "Use the supported skills API surface without crossing into workspace admin.",
    });
    expect(row.commands).toContainEqual({
      name: "Sync companion.json",
      desc: "Create or repair manifest v2 with identity, env/secrets, dependency ids, notes, commands, and changelog.",
    });
    const changelog = row.changes.join("\n");
    expect(changelog).toContain("browser approval");
    expect(changelog).toContain("Cobra command help");
    // SAFETY: the bundled manifest is the repo's own companion.json, whose metadata.changelog shape the manifest schema fixes.
    const manifest = JSON.parse(await readFile(join(skillpackSkillDir(), "companion.json"), "utf8")) as {
      metadata?: { changelog?: Array<{ version?: string; changes?: string[] }> };
    };
    const scheduledRoutineChanges = manifest.metadata?.changelog
      ?.find((entry) => entry.version === "1.109.0")
      ?.changes?.join("\n") ?? "";
    expect(scheduledRoutineChanges).toContain("immutable Skillpack Owner before Box contact");
    expect(scheduledRoutineChanges).toContain("live persistent Skillpack memory");
    expect(scheduledRoutineChanges).toContain("never replays ambiguous or accepted routine work");
    const runtimeRecoveryChanges = manifest.metadata?.changelog
      ?.find((entry) => entry.version === "1.104.1")
      ?.changes?.join("\n") ?? "";
    expect(runtimeRecoveryChanges).toContain("protocol-7 durable cleanup");
    expect(runtimeRecoveryChanges).toContain("message resources");
    expect(runtimeRecoveryChanges).toContain("later FIFO messages");
    const triggerAccountChanges = manifest.metadata?.changelog
      ?.find((entry) => entry.version === "1.101.0")
      ?.changes?.join("\n") ?? "";
    expect(triggerAccountChanges).toContain("provider-account UUIDs");
    expect(triggerAccountChanges).toContain("approving member's sole eligible connection");
    expect(triggerAccountChanges).toContain("fail-closed selection");
    const slackChanges = manifest.metadata?.changelog
      ?.find((entry) => entry.version === "1.92.0")
      ?.changes?.join("\n") ?? "";
    const routineHistoryChanges = manifest.metadata?.changelog
      ?.find((entry) => entry.version === "1.93.0")
      ?.changes?.join("\n") ?? "";
    expect(routineHistoryChanges).toContain("read-only routine run history");
    expect(routineHistoryChanges).toContain("outside delegated Skills Hub Agent Auth");
    expect(slackChanges).toContain("Slack");
    expect(slackChanges).toContain("Slack accounts send through the selected Bot User connection");
    expect(slackChanges).toContain("Events API receive remains a separate trigger increment");
    const triggerRegistrationChanges = manifest.metadata?.changelog
      ?.find((entry) => entry.version === "1.82.0")
      ?.changes?.join("\n") ?? "";
    expect(triggerRegistrationChanges).toContain("propose_trigger");
    expect(triggerRegistrationChanges).toContain("webhook-URL handoff");
    const routineChanges = manifest.metadata?.changelog
      ?.find((entry) => entry.version === "1.78.0")
      ?.changes?.join("\n") ?? "";
    expect(routineChanges).toContain("propose_routine");
    expect(routineChanges).toContain("outside delegated Skills Hub Agent Auth");
    const hubAccessChanges = manifest.metadata?.changelog
      ?.find((entry) => entry.version === "1.76.0")
      ?.changes?.join("\n") ?? "";
    expect(hubAccessChanges).toContain("hosted-Box Skills Hub access is unconditional");
    expect(hubAccessChanges).toContain("refusal means the Skillpack or its member is gone");
    const configProposalChanges = manifest.metadata?.changelog
      ?.find((entry) => entry.version === "1.74.0")
      ?.changes?.join("\n") ?? "";
    expect(configProposalChanges).toContain("propose_config and request_plugin_connection");
    expect(configProposalChanges).toContain("outside delegated Skills Hub Agent Auth");
    const contractProposalChanges = manifest.metadata?.changelog
      ?.find((entry) => entry.version === "1.73.0")
      ?.changes?.join("\n") ?? "";
    expect(contractProposalChanges).toContain("bounded config-proposal decision cards");
    expect(contractProposalChanges).toContain("outside delegated Skills Hub Agent Auth");
    const attachmentsChanges = manifest.metadata?.changelog
      ?.find((entry) => entry.version === "1.72.0")
      ?.changes?.join("\n") ?? "";
    expect(attachmentsChanges).toContain("Skillpack chat attachments were added to the shared contracts");
    const fifoChanges = manifest.metadata?.changelog
      ?.find((entry) => entry.version === "1.66.1")
      ?.changes?.join("\n") ?? "";
    expect(fifoChanges).toContain("anonymous pipe is reported as mode 0660");
    expect(fifoChanges).toContain("named FIFO created at 0600");
    const packageAssemblyChanges = manifest.metadata?.changelog
      ?.find((entry) => entry.version === "1.70.0")
      ?.changes?.join("\n") ?? "";
    expect(packageAssemblyChanges).toContain("package assembly moved out of the retired Box lifecycle code");
    expect(packageAssemblyChanges).toContain("without granting delegated clients any Box or Pi access");
    const asyncRuntimeChanges = manifest.metadata?.changelog
      ?.find((entry) => entry.version === "1.69.0")
      ?.changes?.join("\n") ?? "";
    expect(asyncRuntimeChanges).toContain("durable asynchronous turns and operations");
    expect(asyncRuntimeChanges).toContain("Retry and Cancel recovery for interrupted hosted turns");
    const modelCapabilityChanges = manifest.metadata?.changelog
      ?.find((entry) => entry.version === "1.68.0")
      ?.changes?.join("\n") ?? "";
    expect(modelCapabilityChanges).toContain("model catalog began preserving Pi text and image input capabilities");
    expect(modelCapabilityChanges).toContain("delegated Skills Hub clients gain no hosted runtime access");
    const runtimeBoundaryChanges = manifest.metadata?.changelog
      ?.find((entry) => entry.version === "1.67.0")
      ?.changes?.join("\n") ?? "";
    expect(runtimeBoundaryChanges).toContain("optional hosted Box/Pi teammate runtime");
    expect(runtimeBoundaryChanges).toContain("Agent Auth never grants hosted Skillpack chat");
    const accessibleChanges = manifest.metadata?.changelog
      ?.find((entry) => entry.version === "1.64.0")
      ?.changes?.join("\n") ?? "";
    expect(accessibleChanges).toContain("accessible library listing");
    expect(accessibleChanges).toContain("every org skill plus the caller's own personal skills");
    const memberStateChanges = manifest.metadata?.changelog
      ?.find((entry) => entry.version === "1.59.0")
      ?.changes?.join("\n") ?? "";
    expect(memberStateChanges).toContain("per-member pin, unread, hide, and Owner-only duplicate list actions");
    expect(memberStateChanges).toContain("Skillpack roster preferences and duplicate Box creation");
    const allowDenyChanges = manifest.metadata?.changelog
      ?.find((entry) => entry.version === "1.58.0")
      ?.changes?.join("\n") ?? "";
    expect(allowDenyChanges).toContain("Allow/Deny permission cards for shell, file edits, and questions");
    expect(allowDenyChanges).toContain("Skillpack thread permission decisions and Pi extension UI responses");
    const desktopStreamChanges = manifest.metadata?.changelog
      ?.find((entry) => entry.version === "1.53.0")
      ?.changes?.join("\n") ?? "";
    expect(desktopStreamChanges).toContain("the stream a freshly minted Box desktop arrives over");
    expect(desktopStreamChanges).toContain("the in-thread Box desktop");
    const registryBrowseChanges = manifest.metadata?.changelog
      ?.find((entry) => entry.version === "1.47.0")
      ?.changes?.join("\n") ?? "";
    expect(registryBrowseChanges).toContain("MCP registry browse schema");
    const workspaceShareChanges = manifest.metadata?.changelog
      ?.find((entry) => entry.version === "1.46.0")
      ?.changes?.join("\n") ?? "";
    expect(workspaceShareChanges).toContain("workspace-only access");
    const desktopHandoffChanges = manifest.metadata?.changelog
      ?.find((entry) => entry.version === "1.45.0")
      ?.changes?.join("\n") ?? "";
    expect(desktopHandoffChanges).toContain("Box desktop handoff");
    const pluginAccountChanges = manifest.metadata?.changelog
      ?.find((entry) => entry.version === "1.44.0")
      ?.changes?.join("\n") ?? "";
    expect(pluginAccountChanges).toContain("member-private labeled MCP account metadata");
    const runtimeErrorChanges = manifest.metadata?.changelog
      ?.find((entry) => entry.version === "1.43.0")
      ?.changes?.join("\n") ?? "";
    expect(runtimeErrorChanges).toContain("runtime last_error");
    const threadChanges = manifest.metadata?.changelog
      ?.find((entry) => entry.version === "1.42.0")
      ?.changes?.join("\n") ?? "";
    expect(threadChanges).toContain("1:1 chat thread");
    const sharingChanges = manifest.metadata?.changelog
      ?.find((entry) => entry.version === "1.40.0")
      ?.changes?.join("\n") ?? "";
    expect(sharingChanges).toContain("Owner, Editor, and Viewer sharing");
    expect(sharingChanges).toContain("outside delegated Skills Hub Agent Auth");
    const toolchainChanges = manifest.metadata?.changelog
      ?.find((entry) => entry.version === "1.38.0")
      ?.changes?.join("\n") ?? "";
    expect(toolchainChanges).toContain("published integrity baseline");
    expect(toolchainChanges).toContain("Does not change Skillpack skill commands");
    const grokChanges = manifest.metadata?.changelog
      ?.find((entry) => entry.version === "1.37.0")
      ?.changes?.join("\n") ?? "";
    expect(grokChanges).toContain("Grok Bot");
    expect(grokChanges).toContain("~/.cursor/skills");
    expect(grokChanges).toContain(".cursor/skills");
    expect(grokChanges).toContain("delegated Agent Auth");
    const delegationChanges = manifest.metadata?.changelog
      ?.find((entry) => entry.version === "1.34.0")
      ?.changes?.join("\n") ?? "";
    expect(delegationChanges).toContain("short-lived child PAT issuance");
    expect(delegationChanges).toContain("COMPANION_DELEGATION_TOKEN");
    expect(delegationChanges).toContain("owner-only FIFO");
    expect(delegationChanges).not.toContain("FIFO/socket");
    const databaseChanges = manifest.metadata?.changelog
      ?.find((entry) => entry.version === "1.31.0")
      ?.changes?.join("\n") ?? "";
    expect(databaseChanges).toContain("read-write sharing");
    expect(databaseChanges).toContain("opaque realm selectors");
    const hermesChanges = manifest.metadata?.changelog
      ?.find((entry) => entry.version === "1.32.0")
      ?.changes?.join("\n") ?? "";
    expect(hermesChanges).toContain("~/.hermes/skills");
    expect(hermesChanges).toContain("nested Hermes category skills");
    const lockChanges = manifest.metadata?.changelog?.find((entry) => entry.version === "1.26.4")?.changes?.join("\n") ?? "";
    expect(lockChanges).toContain("credential-lock acquisition");
    expect(lockChanges).toContain("another process releases the shared lock");
    expect(lockChanges).toContain("during inspection");
    const refreshChanges = manifest.metadata?.changelog?.find((entry) => entry.version === "1.23.0")?.changes?.join("\n") ?? "";
    expect(refreshChanges).toContain("Refreshes a file-backed Skillpack token automatically");
    expect(refreshChanges).toContain("Preserves the token's exact name and scopes");
    expect(refreshChanges).toContain("Requires a fresh Use prompt");
    const billingChanges = manifest.metadata?.changelog?.find((entry) => entry.version === "1.19.0")?.changes?.join("\n") ?? "";
    expect(billingChanges).toContain("Documents the managed SaaS Free and Pro skill entitlements");
    expect(billingChanges).toContain("structured entitlement 403 responses");
    // The install prompt drives the native CLI and leaves non-secret placeholders for the client.
    expect(row.prompts.install).toContain("skillpack install skillpack --version");
    expect(row.prompts.install).toContain("skillpack auth login --api-url {base}");
    expect(row.prompts.install).toContain("SKILLPACK_API_KEY");
    expect(row.prompts.install).toContain("skillpack setup --tools");
    expect(row.prompts.install).toContain("{base}");
    expect(row.prompts.install).toContain("{workspaceId}");
    expect(row.prompts.install).not.toContain("{token}");
    expect(row.prompts.install).toContain("Claude Code, Codex, OpenCode, Grok Bot, OpenClaw, or Hermes");
    expect(row.prompts.install).toContain("~/.cursor/skills");
    expect(row.prompts.install).toContain(".cursor/skills");
    expect(row.prompts.install).toContain("Hermes is global-only");
    expect(row.prompts.install).toContain("OpenCode");
    expect(row.prompts.install).toContain("OpenClaw");
    expect(row.prompts.install).toContain(pkg.version);
  });

  it("keeps every generated management prompt on the native API-key CLI flow", () => {
    const prompts = buildSkillpackSkillPrompts("1.26.0");
    const prompt = Object.values(prompts).join("\n");
    expect(prompt).toContain("skillpack auth login --api-url {base}");
    expect(prompt).toContain("skillpack auth status --json");
    expect(prompt).toContain("SKILLPACK_API_KEY");
    expect(prompt).toContain("skillpack update --all --dry-run");
    expect(prompt).toContain("skillpack skills publish FOLDER --scope org");
    expect(prompt).toContain("skillpack api METHOD /v1/path --input FILE");
    expect(prompt).not.toMatch(/Agent Auth|agent-cli|npx\b|python(?:3)?\b|bootstrap\.py|mint a PAT|paste (?:the )?(?:API )?key/i);
    expect(prompts.onboarding).toContain("getting started onboarding");
    expect(prompts.onboarding).toContain("/v1/getting-started");
    expect(prompts.onboarding).toContain("new conversation in {tool}");
    expect(prompts.resume).toContain("first_incomplete_step");
    expect(prompts.resume).toContain("English or French");
  });

  it("bundles native management instructions and legacy in-flight compatibility payload", async () => {
    const skillMd = await readFile(join(skillpackSkillDir(), "SKILL.md"), "utf8");
    const apiRef = await readFile(join(skillpackSkillDir(), "reference", "api.md"), "utf8");
    const checkScript = await readFile(join(skillpackSkillDir(), "scripts", "check_updates.py"), "utf8");
    const bootstrapScript = await readFile(join(skillpackSkillDir(), "scripts", "bootstrap.py"), "utf8");
    const bootstrapUpdateScript = await readFile(join(skillpackSkillDir(), "scripts", "bootstrap_update.py"), "utf8");
    const skillpackLib = await readFile(join(skillpackSkillDir(), "scripts", "companion_lib.py"), "utf8");
    const guardScript = await readFile(join(skillpackSkillDir(), "scripts", "skill_guard.py"), "utf8");
    expect(skillMd).not.toContain("companion_version:");
    expect(skillMd).toContain("compatibility: claude-code codex opencode grok-bot");
    expect(skillMd).toContain("companion.json");
    for (const command of [
      "skillpack auth status --json", "skillpack auth login --api-url",
      "skillpack skills validate", "skillpack skills publish", "skillpack install",
      "skillpack update --all", "skillpack sync --frozen", "skillpack secrets sync",
      "skillpack db query", "skillpack self update", "skillpack doctor --json",
    ]) expect(skillMd).toContain(command);
    expect(skillMd).toContain("skills.lock.json");
    expect(skillMd).toContain("Old limited keys stay limited");
    expect(skillMd).toContain("same-slug, different-content");
    expect(skillMd).toContain("Re-publishing preserves existing labels");
    expect(skillMd).toContain("server remains authoritative");
    expect(skillMd).toContain("compatibility payload");
    expect(skillMd).not.toContain("python3 scripts/");
    expect(skillMd).not.toContain("## Mandatory startup bootstrap");
    expect(apiRef).toContain("`expect_skill_id` / `scope` / `dependency` / `label` fields");
    expect(apiRef).toContain("The Skillpack skill must send `scope=personal` or `scope=org`");
    expect(apiRef).toContain(
      "POST /skills?action=publish&expect_slug=my-skill&version=1.0.0&scope=org&label=marketing&label=marketing%2Fseo",
    );
    expect(apiRef).toContain(
      "POST /skills?action=publish&expect_slug=my-skill&version=1.0.0&scope=personal",
    );
    expect(apiRef).toContain("GET /v1/schemas/companion-manifest.v2.schema.json");
    expect(apiRef).toContain("POST /tokens/refresh");
    expect(apiRef).toContain("GET /skills?lib=mine");
    expect(apiRef).toContain("| Get skill metadata | `GET /skills/{slug}` | `skills:read` |");
    expect(apiRef).toContain("GET /skills?installed=true");
    expect(apiRef).toContain("Read org skill naming policy");
    expect(apiRef).toContain("GET /v1/orgs/current/skill-naming-policy");
    expect(apiRef).toContain("GET /orgs/current/skill-naming-policy");
    expect(apiRef).toContain("The response is `{ \"policy\": string | null }`");
    expect(apiRef).toContain("The only org-settings surface in the closed Skillpack capability registry");
    expect(apiRef).toContain("GET /public/skills/{share_token}");
    expect(apiRef).toContain("Rows also include `share_token`");
    expect(apiRef).toContain("After a successful skill upload or update");
    expect(apiRef).toContain("Skill link: ...");
    expect(apiRef).toContain("Local manifest checks");
    expect(apiRef).toContain("scripts/bootstrap.py");
    expect(apiRef).toContain("integrity.packageChecksum");
    expect(apiRef).toContain("local_customizations");
    expect(apiRef).toContain("never executes the script");
    expect(apiRef).toContain("COMPANION_WORKSPACE_ID");
    expect(apiRef).toContain("skills.log.json");
    expect(apiRef).toContain("response includes `workspaceId`");
    expect(apiRef).toContain("POST /skills/{slug}/install");
    expect(apiRef).toContain("Claude Code, Codex, OpenCode");
    expect(apiRef).toContain("updates preserve the existing scope");
    expect(apiRef).toContain("skill must not declare `scope` or `visibility`");
    expect(apiRef).toContain("Re-publish never moves, adds, or removes folder labels");
    expect(apiRef).toContain("registered package download operation does not expose");
    expect(apiRef).toContain("Personal folder routes use the same request bodies and response shapes");
    expect(apiRef).not.toContain("defaults to `org`");
    expect(apiRef).not.toMatch(/owner_team[\s\S]{0,120}`scope`[\s\S]{0,120}parameters (?:is|are) rejected/);
    expect(skillpackLib).toContain("def resolve_credentials");
    expect(checkScript).toContain("bootstrap.main()");
    expect(bootstrapScript).toContain("/skills?installed=true");
    expect(bootstrapScript).toContain("/local-skills/skillpack");
    expect(bootstrapUpdateScript).toContain("local_customizations");
    expect(bootstrapScript).toContain("from companion_lib import");
    // The anti-duplication / anti-retargeting guard ships alongside the update check.
    expect(guardScript).toContain("def detect_conflicts");
    expect(guardScript).toContain("def create_preflight");
    expect(guardScript).toContain("def migrate_legacy_log");
  });

  it("reflects an install record as installed/update", async () => {
    const pkg = await getSkillpackSkillPackage();
    const base = {
      skillKey: "companion",
      agentLabel: "Claude Code",
      installedAt: new Date("2026-06-15T00:00:00.000Z"),
      lastReportedAt: new Date("2026-06-15T00:00:00.000Z"),
    };
    const current = await buildSkillpackSkillRow({ ...base, installedVersion: pkg.version }, workspaceId);
    expect(current.status).toBe("installed");
    expect(current.lastReportedAt).not.toBeNull();

    const behind = await buildSkillpackSkillRow({ ...base, installedVersion: "0.0.1" }, workspaceId);
    expect(behind.status).toBe("update");
  });
});
